src/MicroweberPackages/Checkout/routes/web.php
<?php

// Private
Route::name('checkout.')
   // ->prefix(multilanguage_route_prefix('checkout'))
    ->middleware([
        \MicroweberPackages\App\Http\Middleware\VerifyCsrfToken::class,
       \MicroweberPackages\Checkout\Http\Middleware\CheckoutV2::class,
       \MicroweberPackages\App\Http\Middleware\XSS::class
   ])
    ->namespace('\MicroweberPackages\Checkout\Http\Controllers')
    ->group(function () {

        // Contact info
        Route::get('cart', 'CheckoutController@index')->name('cart');
        Route::get('contact-information', 'CheckoutController@contactInformation')->name('contact_information');
        Route::post('contact-information-save', 'CheckoutController@contactInformationSave')->name('contact_information_save');

        // Shipping info
        Route::get('shipping-method', 'CheckoutController@shippingMethod')->name('shipping_method');
        Route::post('shipping-method-change', 'CheckoutController@shippingMethodChange')->name('shipping_method_change');
        Route::post('shipping-method-save', 'CheckoutController@shippingMethodSave')->name('shipping_method_save');

        // Payment method
        Route::get('payment-method', 'CheckoutController@paymentMethod')->name('payment_method');
        Route::post('payment-method-change', 'CheckoutController@paymentMethodChange')->name('payment_method_change');
        Route::post('payment-method-save', 'CheckoutController@paymentMethodSave')->name('payment_method_save');
    });

// Public
Route::name('checkout.')
    //->prefix(multilanguage_route_prefix('checkout'))
    ->namespace('\MicroweberPackages\Checkout\Http\Controllers')
    ->group(function () {
        Route::get('login', 'CheckoutController@login')->name('login');
        Route::get('forgot-password', 'CheckoutController@forgotPassword')->name('forgot_password');
        Route::get('register', 'CheckoutController@register')->name('register');
        Route::get('finish/{id}', 'CheckoutController@finish')->name('finish');
    });

src/MicroweberPackages/Checkout/resources/views/contact_information.blade.php
@extends('checkout::layout')

@section('logo-right-link')
<div class="ml-auto align-self-center">
    <a href="{{ site_url() }}shop" class="btn btn-link text-end text-right">{{ _e('Continue shopping') }}</a>
</div>
@endsection

@section('steps_content')

{{--faila se namira v: /src/MicroweberPackages/Checkout/resources/views/contact_information.blade.php--}}
    <form method="post" action="{{ route('checkout.contact_information_save') }}">
        @csrf
        <div class="mt-5 edit nodrop" field="checkout_personal_information_title">
            <h4 class="mb-0"><?php _e("Personal Information"); ?></h4>
            <small class="text-muted d-block mb-2"> <?php _e("Please fill the fields bellow"); ?></small>
        </div>

        <div class="form-group @if(isset($errors['first_name'])) has-danger @endif">
            <label><?php _e("First Name"); ?></label>
            <input name="first_name" type="text" value="<?php if (!empty($checkout_session['first_name'])) echo $checkout_session['first_name']; ?>" class="form-control @if(isset($errors['first_name'])) is-invalid @endif">

            @if(isset($errors['first_name']))<span class="invalid-feedback">{{$errors['first_name'][0]}}</span>@endif
        </div>
        <div class="form-group @if(isset($errors['last_name'])) has-danger @endif">
            <label><?php _e("Last Name"); ?></label>
            <input name="last_name" type="text" value="<?php if (!empty($checkout_session['last_name'])) echo $checkout_session['last_name']; ?>" class="form-control @if(isset($errors['last_name'])) is-invalid @endif">
            @if(isset($errors['last_name']))<span class="invalid-feedback">{{$errors['last_name'][0]}}</span>@endif
        </div>

        <div class="form-group @if(isset($errors['email'])) has-danger @endif">
            <label><?php _e("Email"); ?></label>
            <input name="email" type="email" value="<?php if (!empty($checkout_session['email'])) echo $checkout_session['email']; ?>" class="form-control @if(isset($errors['email'])) is-invalid @endif">
            @if(isset($errors['email']))<span class="invalid-feedback">{{$errors['email'][0]}}</span>@endif
        </div>

        <div class="form-group @if(isset($errors['phone'])) has-danger @endif">
            <label><?php _e("Phone"); ?></label>
            <input name="phone" type="text" value="<?php if (!empty($checkout_session['phone'])) echo $checkout_session['phone']; ?>" class="form-control @if(isset($errors['phone'])) is-invalid @endif">
            @if(isset($errors['phone']))<span class="invalid-feedback">{{$errors['phone'][0]}}</span>@endif
        </div>

        <button type="submit" class="btn btn-primary w-100 mt-3 js-checkout-continue">{{ _e('Continue') }}</button>
    </form>
@endsection

src/MicroweberPackages/Checkout/resources/views/contact_information_card.blade.php
<div class="card my-3">
    <div class="card-body d-flex p-3">

        <div class="col-8">
            <?php if (is_logged()):  $user = get_user();  ?>
            <?php _e("You are logged as"); ?> <?php echo $user['username']; ?>
                <br><br>
            <?php endif; ?>

            <?php if (empty($checkout_session['email']) || empty($checkout_session['email'])):  ?>
                         <?php _e("No personal information for order"); ?>
                        <?php endif;  ?>

            <?php if (!empty($checkout_session['first_name'])) { echo $checkout_session['first_name']; } ?>
            <?php if (!empty($checkout_session['last_name'])) { echo $checkout_session['last_name'] . '<br />'; } ?>
            <?php if (!empty($checkout_session['phone'])) { echo $checkout_session['phone'] . '<br />'; } ?>
            <?php if (!empty($checkout_session['email'])) { echo $checkout_session['email'] . '<br />'; } ?>
        </div>

        <div class="col-4 justify-content-end text-end text-right align-self-top px-0">
            <a href="{{ route('checkout.contact_information') }}" class="btn btn-link px-0">{{ _e('Edit') }}</a>
        </div>

    </div>
</div>

src/MicroweberPackages/Checkout/resources/views/finish.blade.php
@extends('checkout::layout')

@section('checkout_sidebar')
    <div class="col-lg-6 col-12 checkout-v2-sidebar h-100 d-lg-block d-none">
            <div class="row align-self-center justify-content-center">
                <i class="checkout-v2-finish-icon mdi mdi-checkbox-marked-circle-outline text-center"></i>
            </div>
    </div>
@endsection

@section('content')
    <div class="col-lg-6 col-12 d-flex justify-content-center align-items-center">
        <div class="shop-cart text-center">
            {{--<div class="d-flex justify-content-center">@include('checkout::logo')</div>--}}


            @if (\Session::has('success'))
                <div class="row" >
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action list-group-item-success">{!! \Session::get('success') !!}</li>
                    </ul>
                </div>
            @endif


            @if (\Session::has('error'))
                <div class="row" >
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action list-group-item-danger">{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif


            <div class="edit" field="checkout_finish_message" rel="global">
                <label class="control-label mb-0"><?php _e("Your order is completed"); ?></label>
                <h4><?php _e("Thank you"); ?>!</h4>
            </div>

            <label class="control-label mt-4 mb-0"><?php _e("Order number"); ?></label>
            <h4 dusk="order-number"><?php print($order['id']); ?></h4>

            <div class="edit" field="checkout_finish_button" rel="global">
                <div class="mt-4">
                    <a href="{{ site_url() }}"><?php _e("Go to website"); ?></a>
                </div>
            </div>
        </div>
    </div>
@endsection

src/MicroweberPackages/Checkout/resources/views/forgot_password.blade.php
@extends('checkout::layout')

@section('logo-right-link')
    <div class="ml-auto align-self-center">
        <a href="{{ route('checkout.login') }}" class="btn btn-link text-end text-right">{{ _e('Login') }}</a>
        <a href="{{ route('checkout.register') }}" class="btn btn-link text-end text-right">{{ _e('Register') }}</a>
    </div>
@endsection

@section('steps_content')

    <module type="users/forgot_password" class="no-settings" template="checkout_v2" />
@endsection

src/MicroweberPackages/Checkout/resources/views/index.blade.php
@extends('checkout::layout')

@section('steps_content')
<div class="col-12">
    <a href="{{ site_url() }}" class="btn btn-outline-primary"><i class="mdi mdi-arrow-left"></i> {{ _e('Back to shopping') }}</a>
    <div class="shop-cart" style="margin-top:25px;">
        <module type="shop/cart" template="checkout_v2" class="no-settings" data-checkout-link-enabled="n" />
    </div>
</div>

<div class="col-12">
    <a href="{{ route('checkout.contact_information') }}" class="btn btn-primary">{{ _e('Continue') }}</a>
</div>
@endsection

src/MicroweberPackages/Checkout/resources/views/layout.blade.php
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" <?php print lang_attributes(); ?>>
<head>
    <title></title>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap">

    <script>
        mw.require('icon_selector.js');
        mw.lib.require('bootstrap4');
        mw.lib.require('bootstrap_select');

        mw.iconLoader()
            .addIconSet('materialDesignIcons')
            .addIconSet('fontAwesome')
            .addIconSet('iconsMindLine')
            .addIconSet('iconsMindSolid')
            .addIconSet('mwIcons')
            .addIconSet('materialIcons');
    </script>

    <script>
        $(document).ready(function () {
            $('.selectpicker').selectpicker();
        });
    </script>

    <?php print get_template_stylesheet(); ?>

    <style>
        html, body, section, .row {
            height: 100%;
            min-height: 100%;
        }

        .checkout-v2-sidebar {
            background-color: #f5f5f5;
        }

        .checkout-v2-radio input[type=radio] {
            height: 20px;
        }

        i.shipping-icons-checkout-v2.mdi{
            font-size: 36px;
        }

        i.checkout-v2-finish-icon.mdi{
            font-size: 60px;
            color: #dedede;
            display: flex;
            justify-content: center;
            flex-direction: column;
        }

        .checkout-v2-logo {
            width: 35%;
        }

        .checkout-v2-remove-icon a:hover {
            text-decoration: none;
        }
        .checkout-v2-remove-icon a:active {
            text-decoration: none;
        }

        .checkout-v2-remove-icon:hover {
            color: black!important;
        }

        .checkout-v2-shipping-pickup.card-body {
            background: #f5f5f5;
        }

        .checkout-v2-navbar.navbar-light .navbar-toggler {
            height: 50px;
            width: 100%;
            background: #f5f5f5;
        }

        .mw-order-custom-fields ul {
            list-style-type: none;
            margin-bottom: 0.4rem;
        }

        .mw-order-custom-fields ul li {
            margin-bottom: 5px;
        }

        .checkout-v2-right-column-title {
            margin-top: 7rem;
        }


         .checkout-modal-products-wrapper .checkout-modal-product-list-item {
            font-size: 14px;
            border-bottom: 1px solid rgba(0,0,0,.125);
            padding: 10px 0;
            align-items: center;
            justify-content: center;
        }


        .checkout-modal-products-wrapper .products {
            max-height: 400px;
            overflow: auto;
            overflow-x: hidden;
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .ul {
            list-style-type: none;
            margin-bottom: 0.4rem;
        }

        @media screen and (max-width: 767px) {
             .checkout-modal-products-wrapper .checkout-modal-product-list-item img {
                max-width: 200px;
                margin: 0 auto;
                display: block
            }
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item:hover {
            background: #fff
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-action {
            padding-left: 0;
            padding-right: 0
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-action a {
            color: #282627;
            opacity: 1;
            display: inline-block
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-qty {
            padding-left: 0;
            padding-right: 0;
            text-align: center
        }

        .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-qty select {
            margin-top: 25px
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-action .tooltip {
            margin-top: 5px
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-action, .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-price, .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-title {
            /*padding-top: 35px;*/
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis
        }

         .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-action, .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-price {
            text-align: center
        }

         .checkout-modal-amount-holder .checkout-modal-promocode-holder, .checkout-modal-amount-holder .checkout-modal-total-holder {
            /*padding-top: 35px*/
        }


         .checkout-modal-amount-holder .checkout-modal-promocode-holder p, .checkout-modal-amount-holder .checkout-modal-total-holder p {
            margin-bottom: 20px
        }

         .checkout-modal-amount-holder .checkout-modal-promocode-holder .form-control {
            margin: 0
        }

         .checkout-modal-amount-holder .checkout-modal-total-holder, .js-step-content {
            font-size: 16px
        }


        .checkout-modal-total-price {
            font-weight: bold;
        }


        .checkout-modal-products-wrapper .table *{
            vertical-align:middle;
        }
        .checkout-modal-products-wrapper .table .td-title{
            max-width: 140px;
        }
        /* End of */


        /* End of .modal-content */


        @media screen and (max-width: 767px) {
            .checkout-modal-products-wrapper .checkout-modal-product-list-item .checkout-modal-product-list-item-title {
                text-align: center
            }
        }

        @media (min-width: 1450px) {
            .modal-dialog {
                width: 700px
            }
        }
    </style>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<script type="text/javascript">
    mw.require("<?php print(mw_includes_url()); ?>css/ui.css");
    mw.lib.require("bootstrap4");
</script>

@hasSection('checkout_sidebar')

@else

<nav class="navbar-expand-lg checkout-v2-navbar navbar-light d-lg-none d-block">
    <div class="row">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon float-left ml-3"></span>
            <?php $cart_totals = mw()->cart_manager->totals(); ?>
            <?php if ($cart_totals): ?>
            <?php $print_total = cart_total(); ?>
            <h4 class="checkout-modal-total-label float-right mr-3"><?php _lang("Total"); ?>:<?php print currency_format($print_total); ?></h4>
            <?php endif; ?>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            @hasSection('checkout_sidebar')
                @yield('checkout_sidebar')
            @else
                <div class="checkout-v2-sidebar right-column col-12">
                    <div class="col-lg-10 col-12 checkout-v2-right-column float-lg-left p-xl-5 p-md-3 p-3">
                        <div class="text-start text-left">
                            <h6 class="m-t-100"><?php _e("Your order"); ?></h6>
                            <small class="text-muted d-block mb-2"> <?php _e("List with products"); ?></small>
                        </div>

                        <div class="mt-3">
                            <module type="shop/cart" class="no-settings" template="checkout_v2_sidebar" data-checkout-link-enabled="n"/>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
</nav>

@endif

<div class="row">

    @include('checkout::steps_layout')

    @hasSection('content')
        @yield('content')
    @endif

    @hasSection('checkout_sidebar')
        @yield('checkout_sidebar')
    @else
        <div class="checkout-v2-sidebar right-column col-6 d-lg-block d-none">
            <div class="col-lg-10 col-12 checkout-v2-right-column float-lg-left p-xl-5 p-md-3 p-3">
                <div class="text-start text-left">
                    <h6 class="checkout-v2-right-column-title font-weight-bold"><?php _e("Your order"); ?></h6>
                    <small class="text-muted d-block mb-2"> <?php _e("List with products"); ?></small>
                </div>

                <div class="mt-3">
                    <module type="shop/cart" class="no-settings" template="checkout_v2_sidebar" data-checkout-link-enabled="n"/>
                </div>
            </div>
        </div>
    @endif
</div>
</body>
</html>

src/MicroweberPackages/Checkout/resources/views/login.blade.php
@extends('checkout::layout')

@section('steps_content')
    <module type="users/login" class="no-settings" template="checkout_v2" />
@endsection

src/MicroweberPackages/Checkout/resources/views/logo.blade.php
@php
    $logo = get_option('logo', 'website');
@endphp
@if(empty($logo))
    <div>
        <h4><a href="{{ site_url() }}">{{get_option('website_title', 'website')}}</a></h4>
    </div>
@else
    <div class="checkout-v2-logo">
        <a href="{{ site_url() }}">
         <img src="{{ $logo }}"/>
        </a>
    </div>
@endif

@yield('logo-right-link')
@hasSection('logo-right-link')
@endif

src/MicroweberPackages/Checkout/resources/views/payment_method.blade.php
@extends('checkout::layout')


@section('logo-right-link')
    <div class="ml-auto align-self-center">
        <a href="{{ route('checkout.shipping_method') }}" class="btn btn-link text-end text-right">{{ _e('Back') }}</a>
    </div>
@endsection

@section('steps_content')
    @if (isset($errors))
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors as $fields)
                    @foreach ($fields as $field)
                        @if (is_string($field))
                        <li>{!! $field !!}</li>
                        @else
                            <li>  {{_e('Error when trying to finish the payment')}}</li>
                        @endif
                    @endforeach
                @endforeach
            </ul>
        </div>
    @endif

    <form method="post" action="{{ route('checkout.payment_method_save') }}">

        @csrf

        <div class="shop-cart mt-5">
            <label class="font-weight-bold control-label mb-0"><?php _e("Personal information"); ?></label>
            <small class="text-muted d-block mb-2"> <?php _e("Your information"); ?></small>

            @include('checkout::contact_information_card')

            <?php
            if (!empty($checkout_session['shipping_gw'])) {
            $shippingGatewayModuleInfo = module_info($checkout_session['shipping_gw']);
            ?>

            <label class="font-weight-bold control-label mb-0 pt-2"><?php _e("Shipping method"); ?></label>
            <small class="text-muted d-block mb-2"> <?php _e("Your choice"); ?></small>

            <div class="card mb-3">
                <div class="card-body d-flex p-3">
                    <div class="col-8">


                                <?php if (isset($shippingGatewayModuleInfo['settings']['icon_class'])): ?>
                            <i class="<?php echo $shippingGatewayModuleInfo['settings']['icon_class'];?>" style="font-size:38px"></i>
                            <?php endif; ?>

                            <?php echo $shippingGatewayModuleInfo['name'];?>

                            <?php
                            $instructions = app()->shipping_manager->driver($checkout_session['shipping_gw'])->instructions($checkout_session);
                            if (!empty($instructions)) {
                                echo '<br />' . $instructions;
                            }
                            ?>


                        <?php if(!empty($checkout_session['country'])):?>
                            <br><br>
                            <?php if (!empty($checkout_session['country'])) { echo $checkout_session['country']; } ?>
                            <?php if (!empty($checkout_session['city'])) {  echo ', ' . $checkout_session['city']; } ?>
                            <?php if (!empty($checkout_session['address'])) { echo  ', ' .  $checkout_session['address']; } ?>
                            <?php if (!empty($checkout_session['zip'])) { echo  ',  ' .  $checkout_session['zip'] . '<br />'; } ?>

                            <?php if (!empty($checkout_session['other_info'])) { echo '<div class="mt-2"><i class="mdi mdi-comment"></i> ' .  $checkout_session['other_info'] . '<br /></div>'; } ?>

                        <?php endif; ?>
                    </div>

                    <div class="col-4 justify-content-end text-end text-right align-self-top px-0">
                        <a href="{{ route('checkout.shipping_method') }}" class="btn btn-link px-0">{{ _e('Edit') }}</a>
                    </div>
                </div>
            </div>
            <?php } ?>
            <module type="shop/payments" @if(isset($checkout_session['payment_gw'])) selected_provider="{{$checkout_session['payment_gw']}}" @endif  template="checkout_v2" />

            <module type="shop/checkout/terms" template="checkout_v2" class="no-settings" />
        </div>
        <button type="submit" class="btn btn-primary w-100 js-finish-your-order js-checkout-continue"> {{ _e('Complete your order') }}</button>
    </form>

@endsection

src/MicroweberPackages/Checkout/resources/views/register.blade.php
@extends('checkout::layout')

@section('steps_content')
    <module type="users/register" template="checkout_v2" class="no-settings" />
@endsection

src/MicroweberPackages/Checkout/resources/views/shipping_method.blade.php
@extends('checkout::layout')

@section('logo-right-link')
    <div class="ml-auto align-self-center">
        <a href="{{ route('checkout.contact_information') }}" class="btn btn-link text-end text-right">{{ _e('Back') }}</a>
    </div>
@endsection

@section('steps_content')

    @if (isset($errors))
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors as $fields)
                    @foreach ($fields as $field)
                        <li>{!! $field !!}</li>
                    @endforeach
                @endforeach
            </ul>
        </div>
    @endif

    <form method="post" action="{{ route('checkout.shipping_method_save') }}">
        @csrf
        <div class="shop-cart mt-5">
            <label class="font-weight-bold control-label mb-0"><?php _e("Personal information"); ?></label>
            <small class="text-muted d-block mb-2"> <?php _e("Your information"); ?></small>

            @include('checkout::contact_information_card')

            <div class="shop-cart-shipping mb-3">
                 <module type="shop/shipping" class="no-settings" @if(isset($checkout_session['shipping_gw'])) selected_provider="{{$checkout_session['shipping_gw']}}" @endif template="checkout_v2" data-store-values="true" />
            </div>
        </div>

        <button type="submit" class="btn btn-primary w-100 js-checkout-continue">{{ _e('Continue') }}</button>
    </form>
@endsection

src/MicroweberPackages/Checkout/resources/views/steps_layout.blade.php
@hasSection('steps_content')
<div class="col-lg-6 col-12 order-lg-0 order-1">
    <div class="col-lg-8 col checkout-v2-left-column float-lg-right p-xl-5 p-md-3 p-3">

        <div class="d-flex">
            @include('checkout::logo')
        </div>

        @yield('steps_content')
    </div>
</div>
@endif